### ISSUE TITLE
Possibility to provide url positional args

### ISSUE THREAD

**Issue by yunmanger1** [steelkiwi/django-skd-smoke#19]
Not all urls use named arguments. For example django admin is using positional args.

**Comment by ghost** [comment]
@yunmanger1 thank for pointing this out, could you please provide tests for this case?

**Comment by bellum** [comment]
@yunmanger1 Thank you. Feature is implemented in https://github.com/steelkiwi/django-skd-smoke/pull/21 and merged to master.

**Comment by yunmanger1** [comment]
:+1:
